/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "identities"
include(
    "identities-api",
    "identities-squirtgun",
    "identities-bukkit",
    "identities-bungee",
    "identities-discord"
)