name: ProNouns
version: ${project.version}
main: me.lucyy.pronouns.ProNouns
api-version: 1.15
softdepend: [ PlaceholderAPI ]
authors: [ __lucyy ]
description: Putting the "pro" in "pronouns".
website: https://lucyy.me

commands:
  pronouns:
    usage: 'Usage: /pronouns'