# ProNouns Config File
# Make changes here and update them by either using /pronouns reload
# or by restarting the server
# NOTE: if you're using predefined sets with MySQL, make sure they match on
# all servers!

accent: '&d'
main: '&f'
checkForUpdates: true

# this setting chooses how pronouns are stored, possible values:
# yml (default) - creates 'datastore.yml' in plugin folder
# mysql - connects to the mysql database, configured below

connection: 'yml'
#connection: 'mysql'

# this info will be provided by your host
mysql:
  host: '127.0.0.1'
  port: 3306
  database: 'pronouns'
  username: 'pronouns'
  password: 'password'