name: ProNouns
version: @version@
main: net.lucypoulton.pronouns.bukkit.ProNounsBukkit
api-version: 1.13
authors: [ __lucyy ]
description: 'Putting the "pro" in "pronouns".'
website: https://lucyy.me
softdepend:  [ PlaceholderAPI ]
commands:
  pronouns:
    usage: 'Usage: /pronouns'
    aliases: [ 'pn' ]

permissions:
  pronouns.bypass:
    description: "Bypass the filter for setting pronouns"
    default: op
  pronouns.admin:
    description: "Access to admin commands - run commands as other users"
    default: op
