name: ProNouns
version: @version@
main: me.lucyy.pronouns.bukkit.ProNounsBukkit
api-version: 1.16
authors: [ __lucyy ]
description: Putting the "pro" in "pronouns".
website: https://lucyy.me
loadbefore: [ PlaceholderAPI ]
commands:
  pronouns:
    usage: 'Usage: /pronouns'

permissions:
  pronouns.bypass:
    description: "Bypass the filter for setting pronouns"
    default: op
  pronouns.admin:
    description: "Access to admin commands - run commands as other users"
    default: op
